--Renomear coluna com SP_rename

SP_Rename 'TBL_LIVROS.Nome_Livro', 'Titulo_Livro', 'COLUMN'
Select * from  TBL_LIVROS

--ALTER TABLE, EXCLUINDO E RECRIANDO UMA COLUNA

ALTER TABle TBL_LIVROS DROP CONSTRAINT FK_ID_AUTOR

ALTER TABle TBL_LIVROS DROP COLUMN ID_AUTOR

SELECT * FROM TBL_LIVROS

ALTER TABLE TBL_LIVROS ADD ID_Autor SMALLINT NOT NULL
CONSTRAINT FK_ID_AUTOR FOREIGN KEY (ID_AUTOR) 
REFERENCES TBL_AUTORES (ID_AUTOR)

SELECT * FROM TBL_LIVROS

--ADICIONADO CHAVE ESTRANGEIRA

ALTER TABLE TBL_LIVROS ADD ID_Editora SMALLINT NOT NULL
CONSTRAINT FK_ID_EDITORA FOREIGN KEY (ID_EDITORA)
REFERENCES TBL_EDITORAS (ID_EDITORA)
ON DELETE CASCADE

SELECT * FROM TBL_LIVROS