CREATE TABLE TBL_GENEROS 
(
ID_Genero TINYINT IDENTITY,
Nome_Genero VARCHAR(25),
)

ALTER TABLE TBL_GENEROS 
ADD CONSTRAINT PK_ID_GENERO PRIMARY KEY (ID_Genero)

ALTER TABLE TBL_LIVROS 
ADD ID_Genero TINYINT CONSTRAINT FK_ID_GENERO FOREIGN KEY (ID_Genero)
REFERENCES TBL_GENEROS (ID_Genero)
ON DELETE CASCADE

