SELECT MAX(ID_Autor) AS Maior_ID_Autor FROM PDI..TBL_AUTORES

SELECT MIN(ID_Autor) AS Menor_ID_Autor FROM PDI..TBL_AUTORES

SELECT AVG(Preco_Livro) AS Media_Preco FROM PDI..TBL_LIVROS

SELECT SUM(Preco_Livro) AS Soma_Preco FROM PDI..TBL_LIVROS

SELECT COUNT(ID_Livro) AS Qtd_Livros FROM PDI..TBL_LIVROS

