DECLARE
@TOTAL AS FLOAT,
@DESCONTO VARCHAR (25),
@VENDA INT

SET @VENDA = 12

SELECT 
@TOTAL = (QTD_LIVROS * PRECO_LIVRO)
FROM PDI..TBL_VENDA AS V
JOIN PDI..TBL_LIVROS AS L ON V.ID_LIVRO = L.ID_LIVRO
WHERE ID_VENDA = @VENDA
IF @TOTAL < 100
	BEGIN
	SELECT @DESCONTO = 'Não tem desconto'
	END
IF @TOTAL >= 100
	BEGIN
		SELECT @DESCONTO = '10% DE desconto'
	END
IF @TOTAL >= 200
	BEGIN
		SELECT @DESCONTO = '20% DE desconto'
	END

SELECT @DESCONTO AS DESCONTO 