--INDICES DEVEM SER USADOS EM TABELAS AONDE SE HÁ MUITAS CONSULTAS 
--POIS PODEM DEIXAR A ATUALIZAÇÃO MAIS LENTA, PORÉM OTIMIZAM CONSULTAS

USE PDI 
CREATE INDEX INDICE_TITULO_LIVRO
ON TBL_LIVROS(Titulo_Livro)

--O INDEX PODE SER VISTO NO PESQUISADOR DE OBJETOS NA ABA DE INDICES DA TABELA