--IMPLEMENTA PARÂMETROS PARA COLUNAS E TABELAS

--CRIA REGRA
CREATE RULE REGRA_DE_PRECO
AS @VALOR > 10.00

--IMPLEMENTA REGRA
EXECUTE SP_BINDRULE REGRA_DE_PRECO,
'TBL_LIVROS.Preco_Livro'

--TESTE
SELECT * FROM TBL_LIVROS
UPDATE TBL_LIVROS SET Preco_Livro = 5.00 WHERE ID_Livro = 101