SELECT Titulo_Livro FROM PDI..TBL_LIVROS 

SELECT * FROM PDI..TBL_LIVROS 

SELECT * FROM PDI..TBL_LIVROS ORDER BY ID_AUTOR DESC

SELECT * FROM PDI..TBL_LIVROS ORDER BY ID_AUTOR ASC

SELECT DISTINCT Nome_Editora FROM PDI..TBL_EDITORAS

SELECT * FROM PDI..TBL_LIVROS WHERE ID_Livro = 102

SELECT * FROM PDI..TBL_LIVROS WHERE ID_Livro > 102

SELECT * FROM PDI..TBL_LIVROS WHERE ID_Livro <> 102

SELECT * FROM PDI..TBL_LIVROS WHERE ID_Livro BETWEEN 102 AND 104

SELECT TOP 1 * FROM PDI..TBL_LIVROS

SELECT TOP 50 PERCENT * FROM PDI..TBL_LIVROS

SELECT * FROM PDI..TBL_LIVROS WHERE Titulo_Livro LIKE '%Sub%'

SELECT * FROM PDI..TBL_LIVROS WHERE Titulo_Livro NOT LIKE '%Sub%'

SELECT * FROM PDI..TBL_LIVROS WHERE ID_Livro IN (102, 104)

SELECT * FROM PDI..TBL_LIVROS WHERE ID_Livro NOT IN (102, 104)

SELECT TOP 10 PERCENT Titulo_Livro FROM PDI..TBL_LIVROS WHERE ID_Livro = 104 ORDER BY ID_Autor DESC

SELECT TOP 2 WITH TIES * FROM PDI..TBL_LIVROS ORDER BY Preco_Livro 