DECLARE @ISBN AS VARCHAR(30)

SET @ISBN = '9788556510259'

SELECT * FROM PDI..TBL_LIVROS WHERE ISBN = @ISBN

---------------------------------------------------
DECLARE @ISBN AS VARCHAR(30)
, @PRECO MONEY
, @QUANTIDADE INT

SET @QUANTIDADE = 5

SELECT @ISBN = ISBN, @PRECO = Preco_Livro
FROM PDI..TBL_LIVROS 
WHERE ID_LIVRO = 101

SELECT @ISBN AS ISBN, @PRECO * @QUANTIDADE AS Total
