
USE PDI
CREATE TABLE TBL_CLIENTES
(
ID_Cliente SMALLINT IDENTITY(100, 1),
Nome_Cliente VARCHAR(50) NOT NULL,
CPF VARCHAR(30) NOT NULL UNIQUE,
Data_Nascimento DATE NOT NULL,
)

ALTER TABLE TBL_CLIENTES 
ADD CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_Cliente)

SP_HELP TBL_CLIENTES

DROP TABLE TBL_CLIENTES

SP_HELP TBL_CLIENTES