ALTER TABLE TBL_AUTORES
DISABLE TRIGGER INSERCAO1

ALTER TABLE TBL_AUTORES
ENABLE TRIGGER INSERCAO1

ALTER TABLE TBL_AUTORES
DISABLE TRIGGER INSERCAO_INVES_DE

ALTER TABLE TBL_AUTORES
ENABLE TRIGGER INSERCAO_INVES_DE