
USE PDI
CREATE TABLE TBL_CLIENTES
(
ID_Cliente SMALLINT IDENTITY(100, 1),
Nome_Cliente VARCHAR(50) NOT NULL,
CPF VARCHAR(30) NOT NULL UNIQUE,
Data_Nascimento DATE NOT NULL,
)

ALTER TABLE TBL_CLIENTES 
ADD CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_Cliente)


INSERT INTO TBL_CLIENTES (Nome_Cliente, CPF, Data_Nascimento)
VALUES ('Fulano', '12334578962', '19990101'),
('Ciclano', '00000000000', '20020101')

SELECT * FROM TBL_CLIENTES

TRUNCATE TABLE TBL_CLIENTES

SELECT * FROM TBL_CLIENTES

DROP TABLE TBL_CLIENTES