EXEC sp_helptrigger @TABNAME = TBL_EDITORAS
EXEC sp_helptrigger @TABNAME = TBL_AUTORES

USE PDI
SELECT * FROM SYS.triggers
WHERE IS_DISABLED = 0

USE PDI
SELECT * FROM SYS.triggers
WHERE IS_DISABLED = 1